# Generated by Django 5.0.3 on 2024-05-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_category_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='companyName',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='Vendor_imgs/'),
        ),
    ]
