# Generated by Django 5.0.3 on 2024-05-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vendor_companyname_vendor_mobile_vendor_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='companyName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
