# Generated by Django 5.0.3 on 2024-05-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vendor_companyname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='companyName',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.CharField(default='default address', max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
