# Generated by Django 5.0.3 on 2024-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_buyer_companyname_buyer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='default address', max_length=255),
        ),
    ]
