# Generated by Django 5.0.3 on 2024-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='buyer_imgs/'),
        ),
    ]
