# Generated by Django 5.0.3 on 2024-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='companyName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
