# Generated by Django 5.0.3 on 2024-09-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_store_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(choices=[('Croco nutrition', 'Croco Nutrition'), ('Croco wear', 'Croco Wear'), ('Croco team', 'Croco Team')], max_length=50, unique=True),
        ),
    ]
