# Generated by Django 5.0.3 on 2024-09-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
