# Generated by Django 5.0.3 on 2024-09-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_product_store_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Croco nutrition', 'Croco Nutrition'), ('Croco wear', 'Croco Wear'), ('Croco team', 'Croco Team')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CrocoTeamProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_details', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='CrocoTeamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='croco_team_imgs/')),
                ('team_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.crocoteamproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CrocoTeamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='croco_team_videos/')),
                ('team_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.crocoteamproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CrocoWearProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wear_details', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.store'),
        ),
    ]
