# Generated by Django 5.0.3 on 2024-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_crocowearproduct_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crocowearproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crocowearproduct',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CrocoNutritionProduct',
        ),
    ]
