# Generated by Django 5.0.3 on 2024-09-27 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_product_colors_remove_product_flavor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.CreateModel(
            name='CrocoNutritionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_details', to='main.product')),
            ],
        ),
    ]
