# Generated by Django 5.0.3 on 2024-09-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_product_color_remove_product_flavor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrocoNutritionProduct',
        ),
    ]
