# Generated by Django 5.0.3 on 2024-09-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_croconutritionproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crocoteamproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='crocoteamvideo',
            name='team_product',
        ),
        migrations.RemoveField(
            model_name='crocowearproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='CrocoTeamImage',
        ),
        migrations.DeleteModel(
            name='CrocoTeamProduct',
        ),
        migrations.DeleteModel(
            name='CrocoTeamVideo',
        ),
        migrations.DeleteModel(
            name='CrocoWearProduct',
        ),
    ]
