# Generated by Django 5.1.1 on 2024-10-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_product_color_product_expiration_date_product_flavor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
